/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erma
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
         setDate(); setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labeltanggal = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nama = new javax.swing.JLabel();
        Minuman = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Harga_makanan = new javax.swing.JTextField();
        Harga_minuman = new javax.swing.JTextField();
        Jumlah_minuman = new javax.swing.JTextField();
        Makanan = new javax.swing.JTextField();
        minum = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Jumlah_makanan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        clear = new javax.swing.JButton();
        save = new javax.swing.JButton();
        print = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        keluar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dis = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 153, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Erma's Food");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 10, 342, 49);

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("Our Daily Nutrition");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 60, 220, 21);

        labeltanggal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeltanggal.setText("Tanggal");
        jPanel1.add(labeltanggal);
        labeltanggal.setBounds(729, 11, 115, 22);

        labeljam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labeljam.setText("Pukul");
        jPanel1.add(labeljam);
        labeljam.setBounds(729, 39, 100, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal     :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(600, 14, 80, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Pukul         :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(600, 39, 79, 17);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 920, 100);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Isian Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jPanel2.setLayout(null);

        nama.setText("Nama Makanan");
        jPanel2.add(nama);
        nama.setBounds(10, 33, 87, 30);
        jPanel2.add(Minuman);
        Minuman.setBounds(115, 156, 185, 36);

        jLabel3.setText("Harga");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 70, 60, 30);
        jPanel2.add(Harga_makanan);
        Harga_makanan.setBounds(115, 72, 185, 36);
        jPanel2.add(Harga_minuman);
        Harga_minuman.setBounds(115, 198, 185, 36);
        jPanel2.add(Jumlah_minuman);
        Jumlah_minuman.setBounds(115, 243, 185, 36);

        Makanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakananActionPerformed(evt);
            }
        });
        jPanel2.add(Makanan);
        Makanan.setBounds(115, 30, 185, 36);

        minum.setText("Nama Minuman");
        jPanel2.add(minum);
        minum.setBounds(10, 167, 100, 14);

        harga.setText("Harga");
        jPanel2.add(harga);
        harga.setBounds(10, 209, 70, 14);

        jLabel4.setText("Jumlah");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 254, 60, 14);
        jPanel2.add(Jumlah_makanan);
        Jumlah_makanan.setBounds(115, 114, 185, 36);

        jLabel10.setText("Jumlah");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 114, 80, 31);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 110, 310, 290);
        jPanel2.getAccessibleContext().setAccessibleName("Data Makanan");

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));
        jPanel3.setLayout(null);

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel3.add(clear);
        clear.setBounds(99, 19, 90, 38);

        save.setText("Save");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel3.add(save);
        save.setBounds(10, 20, 79, 37);

        print.setText("Print");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });
        jPanel3.add(print);
        print.setBounds(493, 19, 89, 38);

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel3.add(delete);
        delete.setBounds(395, 19, 88, 38);

        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });
        jPanel3.add(refresh);
        refresh.setBounds(200, 19, 88, 38);

        jButton2.setText("Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(298, 19, 87, 38);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(320, 110, 600, 80);

        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Makanan", "Harga_makanan", "Jumlah_makanan", "Minuman", "Harga_minuman", "Jumlah", "Total"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 200, 600, 230);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(null);

        keluar.setText("Exit");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel4.add(keluar);
        keluar.setBounds(775, 20, 110, 43);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("POTONGAN");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(140, 40, 190, 40);

        Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Total.setText("0");
        jPanel4.add(Total);
        Total.setBounds(370, 0, 140, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("TOTAL BAYAR");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(140, 0, 190, 40);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Rp");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(330, 0, 30, 30);

        dis.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dis.setText("0");
        jPanel4.add(dis);
        dis.setBounds(370, 50, 100, 30);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 450, 920, 80);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Diskon 15% untuk pembelian minimal 200000");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 410, 310, 30);

        setSize(new java.awt.Dimension(938, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Erma's Food");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}       ");
        try {
            tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_printActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
          if ("".equals(Makanan.getText()) || "".equals(Harga_makanan.getText()) || "".equals(Jumlah_makanan.getText())|| "".equals(Minuman.getText()) || "".equals(Harga_minuman.getText()) ||"".equals(Jumlah_minuman.getText())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            int a = Integer.parseInt(Harga_makanan.getText());
            int b = Integer.parseInt(Jumlah_makanan.getText());
            int c = Integer.parseInt(Harga_minuman.getText());
            int d = Integer.parseInt(Jumlah_minuman.getText());
            int total = Integer.parseInt(Total.getText());
            int hasil = ((a*b)+(c*d))+total;
            int diskon = Integer.parseInt(dis.getText());
            
            
              if (hasil >= 200000) {
            diskon = hasil * 15 / 100;
            hasil = hasil - diskon; 
                JOptionPane.showMessageDialog(this, "Diskon 15%", "Selamat", JOptionPane.WARNING_MESSAGE);
            } 
           
       
            
            String ab = Integer.toString(hasil);
            String cd = Integer.toString(diskon);
            String SQL = "INSERT INTO tb_resto VALUES "
                    + "('" + Makanan.getText() + "','" 
                    + Harga_makanan.getText() + "','" 
                    + Jumlah_makanan.getText() + "','"
                    + Minuman.getText() + "','" 
                    + Harga_minuman.getText() + "','" 
                    + Jumlah_minuman.getText() + "','"
                    
                    
                    + hasil + "')";
            
          
            
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                Total.setText(ab); dis.setText(cd); selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
          
                                    

    }//GEN-LAST:event_saveActionPerformed
 
    
    private void MakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MakananActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         int baris = tabel.getSelectedRow();
        if (baris != -1) {
            String id_barang = tabel.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_resto WHERE Makanan='"+Makanan+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
                 
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Barisnya Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }
                                         

    }//GEN-LAST:event_deleteActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        Makanan.setText("");
        Harga_makanan.setText("");
        Jumlah_makanan.setText("");
        Minuman.setText("");
        Harga_minuman.setText("");
        Jumlah_minuman.setText("");
        Total.setText("");
        dis.setText("");
                                
    }//GEN-LAST:event_clearActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        // TODO add your handling code here:
         MessageFormat header = new MessageFormat("Erma's  food");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}       ");
        try {
            tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         int baris = tabel.getSelectedRow();
        String tb_resto = tabel.getValueAt(baris, 0).toString();       
        if ("".equals(Makanan.getText()) || "".equals(Harga_makanan.getText()) || "".equals(Jumlah_makanan.getText()) || "".equals(Minuman.getText()) || "".equals(Harga_minuman.getText())|| "".equals(Jumlah_minuman.getText()) ) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            int a = Integer.parseInt(Harga_makanan.getText());
            int b = Integer.parseInt(Jumlah_makanan.getText());
            int c = Integer.parseInt(Harga_minuman.getText());
            int d = Integer.parseInt(Jumlah_minuman.getText());
            int total = Integer.parseInt(Total.getText());
            int hasil = ((a*b)+(c*d))+total;
            
           
            String SQL = "UPDATE tb_resto SET `makanan`='"+Makanan.getText()
                    +"',`harga_makanan`='"+Harga_makanan.getText()
                    +"',`jumlah_makanan`='"+Jumlah_makanan.getText()
                    +"',`minuman`='"+Minuman.getText()
                    +"',`harga_minuman`='"+Harga_minuman.getText()
                    +"',`jumlah_minuman`='"+Jumlah_minuman.getText()
                    +"',`total_harga`='"+ hasil
                    +"' WHERE makanan="+Makanan;
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data berhasil diupdate","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
          
        }
   
    }                                    

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        String SQL = "DELETE FROM tb_resto";
        int status = KoneksiDB.execute(SQL);
        dispose();
        // TODO add your handling code here:
    }                                        

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {                                         
        MessageFormat header = new MessageFormat("TOKO CETAR JAYA");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}       ");
        try {
            tabel.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e){
            System.err.format("Cannot print %s%n", e.getMessage());
        }
        // TODO add your handling code here:      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
         String SQL = "DELETE FROM tabel";
        int status = KoneksiDB.execute(SQL);
        dispose();
    }//GEN-LAST:event_keluarActionPerformed

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Harga_makanan;
    private javax.swing.JTextField Harga_minuman;
    private javax.swing.JTextField Jumlah_makanan;
    private javax.swing.JTextField Jumlah_minuman;
    private javax.swing.JTextField Makanan;
    private javax.swing.JTextField Minuman;
    private javax.swing.JLabel Total;
    private javax.swing.JButton clear;
    private javax.swing.JButton delete;
    private javax.swing.JLabel dis;
    private javax.swing.JLabel harga;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JLabel minum;
    private javax.swing.JLabel nama;
    private javax.swing.JButton print;
    private javax.swing.JButton refresh;
    private javax.swing.JButton save;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables

 private void selectData() {
    String kolom[] = {"makanan","harga_makanan","jumlah_makanan","minuman","harga_minuman", "jumlah_minuman", "tot"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_resto";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try{
            while(rs.next()){
                String makanan = rs.getString(1);
                String harga1 = rs.getString(2);
                String jumlah1 = rs.getString(3);
                String minuman= rs.getString(4);
                String harga2 = rs.getString(5);
                String jumlah2 = rs.getString(6);
                String data[] = {makanan,harga1,jumlah1,minuman,harga2,jumlah2};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        tabel.setModel(dtm);
    }   
       
    private void setDate() {
        java.util.Date now = new java.util.Date();
        java.text.SimpleDateFormat kal = new java.text.SimpleDateFormat("dd/MM/yyyy");
        labeltanggal.setText(kal.format(now));
    }

    private void setTime() {
         ActionListener taskPerformer = new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                String nol_jam = "";
                String nol_menit = "";
                String nol_detik = "";
                
            Date dt = new Date();
            int nilai_jam = dt.getHours();
            int nilai_menit = dt.getMinutes();
            int nilai_detik = dt.getSeconds();
            
            if (nilai_jam <= 9) {
            nol_jam = "0";
        }
            if (nilai_menit <= 9) {
            nol_menit = "0";
        }
            if (nilai_detik <= 9) {
            nol_detik = "0";
        }
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
            labeljam.setText(jam + " . " + menit + " . " + detik);
        }
    };
        new Timer(100, taskPerformer).start();
}    
}

